FROM clojure

RUN apt-get update && apt-get -y install npm nodejs nodejs-legacy
RUN npm install -g less less-plugin-clean-css less-plugin-autoprefix

VOLUME /app
VOLUME /root/.m2

EXPOSE 3000 3449 7888

WORKDIR /app